### ISSUE TITLE
enlarging the image crash

### ISSUE THREAD

**Issue by springswen** [esimov/caire#95] opened 2023-11-27 03:24 UTC
### Describe the bug
When I convert jpg, it crashes or freezes.

### API related bug
caire -preview=false -width=1168  -height=1024 -face=true -in 5.jpg -out 5-resize.jpg
⚡ CAIRE ⇢ image resizing in progress (be patient, it may take a while)... ⠎⠁

### Screenshots
![image](https://github.com/esimov/caire/assets/34053836/d4960bc8-fd17-47c8-8464-83eeb747985d)

### Bug with the Desktop version (please complete the following information):
 Ubuntu and Windows 10 

### Additional context
The attachment is 5.jpg

![5](https://github.com/esimov/caire/assets/34053836/b7b8e02c-2025-43c3-aac7-66d6e7d64486)

**Comment by esimov** [comment] 2023-12-13 09:09
Closing because I could not reproduce the issue and didn't received any response.

**Closed by esimov** 2023-12-13 09:09 UTC
