### ISSUE TITLE
Square option problem

### ISSUE THREAD

**Issue by zluo01** [esimov/caire#49] opened 2019-06-25 18:06 UTC
Hi, when I try to resize an image with size 2400 * 2400 with setting New_width = 180, scale = true, Square = true, face detection = true, it will not resize the image and output the original image after process, if Square option is removed, then it will resize the image correctly. I wonder if it is config problem or others?

Thank you

**Comment by esimov** [comment] 2019-06-30 04:15
Can you send me the exact command you have tried with? I will try to find the issue.

**Comment by zluo01** [comment] 2019-07-01 00:02
I integrate it into a project. So I pass in value and create Processor struct with setting **New_width = 180, scale = true, Square = true, face detection = true**, the others are all as initial value from a new struct. It will not resize the image properly to 180 * 180 but return 2400*2400. I use the code you provide inside doc.go.

Thank you

**Comment by esimov** [comment] 2019-07-01 14:31
I will take a look and come back to you once I found something.

**Comment by esimov** [comment] 2019-07-08 11:24
Sorry for the late response. I have fixed the reported issue. I haven't checked the possibility, in case the square option is used, that the source image can be also squared. Can you try it now and let me know if it's working for you.

**Comment by esimov** [comment] 2019-07-14 19:29
Closing this issue, since i haven't received any feedback. In case it's still reproducing you can reopen it.

**Closed by esimov** 2019-07-14 19:29 UTC
